[package]
name = "biosctl"
version = "0.3.0-dev"
authors = ["Antoine Gourlay <antoine@gourlay.fr>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"

[dependencies.structopt]
version = '0.3'
default-features = false
features = ['suggestions']

[profile.release]
lto = true
