[package]
name = "firmconfig"
version = "0.1.0"
authors = ["Antoine Gourlay <antoine@gourlay.fr>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"

[dependencies.structopt]
version = '0.3'
default-features = false
features = ['suggestions']