[package]
name = "firmconfig"
version = "0.1.0"
authors = ["Antoine Gourlay <antoine@gourlay.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
